/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Text;
export const MessageId = IDL.Nat;
export const BadgeId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserStats = IDL.Record({
  'lastViewedTimestamp' : Time,
  'messagesViewed' : IDL.Nat,
  'badgesEarned' : IDL.Vec(BadgeId),
});
export const UserProfile = IDL.Record({
  'favorites' : IDL.Vec(MessageId),
  'name' : IDL.Text,
  'stats' : UserStats,
});
export const EncouragementMessage = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'category' : Category,
});
export const RewardBadge = IDL.Record({
  'id' : BadgeId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEncouragementMessage' : IDL.Func([IDL.Text, Category], [MessageId], []),
  'addFavorite' : IDL.Func([MessageId], [], []),
  'addRewardBadge' : IDL.Func([IDL.Text, IDL.Text], [BadgeId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimReward' : IDL.Func([BadgeId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEncouragementMessages' : IDL.Func(
      [],
      [IDL.Vec(EncouragementMessage)],
      ['query'],
    ),
  'getMessagesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(EncouragementMessage)],
      ['query'],
    ),
  'getRewardBadges' : IDL.Func([], [IDL.Vec(RewardBadge)], ['query']),
  'getTodayEncouragement' : IDL.Func([], [IDL.Text], ['query']),
  'getUserFavorites' : IDL.Func([], [IDL.Vec(EncouragementMessage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFavorite' : IDL.Func([MessageId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStats' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Text;
  const MessageId = IDL.Nat;
  const BadgeId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserStats = IDL.Record({
    'lastViewedTimestamp' : Time,
    'messagesViewed' : IDL.Nat,
    'badgesEarned' : IDL.Vec(BadgeId),
  });
  const UserProfile = IDL.Record({
    'favorites' : IDL.Vec(MessageId),
    'name' : IDL.Text,
    'stats' : UserStats,
  });
  const EncouragementMessage = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'category' : Category,
  });
  const RewardBadge = IDL.Record({
    'id' : BadgeId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEncouragementMessage' : IDL.Func([IDL.Text, Category], [MessageId], []),
    'addFavorite' : IDL.Func([MessageId], [], []),
    'addRewardBadge' : IDL.Func([IDL.Text, IDL.Text], [BadgeId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimReward' : IDL.Func([BadgeId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEncouragementMessages' : IDL.Func(
        [],
        [IDL.Vec(EncouragementMessage)],
        ['query'],
      ),
    'getMessagesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(EncouragementMessage)],
        ['query'],
      ),
    'getRewardBadges' : IDL.Func([], [IDL.Vec(RewardBadge)], ['query']),
    'getTodayEncouragement' : IDL.Func([], [IDL.Text], ['query']),
    'getUserFavorites' : IDL.Func(
        [],
        [IDL.Vec(EncouragementMessage)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFavorite' : IDL.Func([MessageId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStats' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };